### ISSUE TITLE
Theme not applying completely

### ISSUE THREAD

**Issue by AlexMax** [AdrianWilczynski/OneDarkPro#2]
This might be my less than thorough familiarity with Visual Studio, but I have found that your color theme seems to apply to the widgets of my editor, but not to the actual code.

![](https://puu.sh/FFmm7/8f9fd0fc06.png)

Any idea what's going on here?

**Comment by AdrianWilczynski** [comment]
It seems like it does kinda apply to code as well (look at the pink/purple keywords for example). 

It's just that I don't really know C++ (it is C++, right? ^^) so I didn't manually edit its syntax highlighting after generating this theme using Dainty. I did it for C# and HTML so that's why that code looks different and closer to original One Dark Pro.

**Comment by AlexMax** [comment]
I understand.  I don't necessarily think you need to know C++.  Seems like you could just open some random C++ file in Visual Studio Code with One Dark Pro applied, use the Inspect Editor Tokens and Scopes tool to figure the color and what kind of token VS Code thinks it is, then just change one of the C++-specific styles in VS until you hit the right color.  That's what I'd do, if I knew anything about VS Community styling in general.

**Comment by AdrianWilczynski** [comment]
You're probably not wrong. I just don't know it, so I don't use it, so I didn't bother 😅 since I feel like it looks acceptable anyway.

If you'd like to take a stab at it you can use https://marketplace.visualstudio.com/items?itemName=ms-madsk.ColorThemeDesigner. It has some kinks but it's rather straightforward to use though looking for the right elements on the list is kinda tedious.

**Comment by AdrianWilczynski** [comment]
Fixed by #5

**Comment by AlexMax** [comment]
@AdrianWilczynski I don't think i properly thanked you for putting in that work, so thanks, the differences were noticed and appreciated, and I still use your theme.

**Comment by AdrianWilczynski** [comment]
You should really thank Eric-Arz because he did all the work on C++ 😅
