### ISSUE TITLE
Theme not applying to certain parts of intellisense tooltips

### ISSUE THREAD

**Issue by rp0m** [AdrianWilczynski/OneDarkPro#4]
![image](https://user-images.githubusercontent.com/38060547/81768303-faa61500-951d-11ea-9c02-65659e1656a6.png)

**Comment by AdrianWilczynski** [comment]
It looks fine on my end. Can you help me reproduce this?

<img width="841" alt="tooltip" src="https://user-images.githubusercontent.com/31390726/81794470-1eac2b00-950b-11ea-90bc-b2c3bcd5ffab.png">

**Comment by stamminator** [comment]
@AdrianWilczynski I am getting the same result @rp0m was getting. Could you please re-open? Here is an example from within a `<script></script>` tag on a .vbhtml page

![image](https://user-images.githubusercontent.com/10633170/113068850-20b3c280-918d-11eb-8886-317010be6f99.png)

And here is an example from a .cs file, specifically an MVC controller

![image](https://user-images.githubusercontent.com/10633170/113069062-8e5fee80-918d-11eb-8245-9243b50c1e47.png)

I did _not_ get this behavior from within my Global.asax.vb file

![image](https://user-images.githubusercontent.com/10633170/113069333-15ad6200-918e-11eb-98ae-2b54f7787821.png)

Nor did I get it inside an actual .js file rather than embedded JS within a .vbhtml Razor view

![image](https://user-images.githubusercontent.com/10633170/113069622-be5bc180-918e-11eb-97cd-94e315aeff58.png)

I tried playing around with the Options > Environment > Fonts and Colors settings from within Visual Studio described [here](https://stackoverflow.com/a/48787913/4028303), but nothing I did affected the bright background color.

I hope this helps narrow it down.
